/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_team254_lib_util_drivers_RPLidarJNI */

#ifndef _Included_com_team254_lib_util_drivers_RPLidarJNI
#define _Included_com_team254_lib_util_drivers_RPLidarJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_team254_lib_util_drivers_RPLidarJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_team254_lib_util_drivers_RPLidarJNI_init
  (JNIEnv *, jobject);

/*
 * Class:     com_team254_lib_util_drivers_RPLidarJNI
 * Method:    checkHealth
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_team254_lib_util_drivers_RPLidarJNI_checkHealth
  (JNIEnv *, jobject);

/*
 * Class:     com_team254_lib_util_drivers_RPLidarJNI
 * Method:    startMotor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_team254_lib_util_drivers_RPLidarJNI_startMotor
  (JNIEnv *, jobject);

/*
 * Class:     com_team254_lib_util_drivers_RPLidarJNI
 * Method:    startScan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_team254_lib_util_drivers_RPLidarJNI_startScan
  (JNIEnv *, jobject);

/*
 * Class:     com_team254_lib_util_drivers_RPLidarJNI
 * Method:    grabScanData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_team254_lib_util_drivers_RPLidarJNI_grabScanData
  (JNIEnv *, jobject);

/*
 * Class:     com_team254_lib_util_drivers_RPLidarJNI
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_team254_lib_util_drivers_RPLidarJNI_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
