/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_team254_lib_util_drivers_RPLidarJNI_DataPoint */

#ifndef _Included_com_team254_lib_util_drivers_RPLidarJNI_DataPoint
#define _Included_com_team254_lib_util_drivers_RPLidarJNI_DataPoint
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
